"""add price_history table

Revision ID: 58acae84c2df
Revises: a250757ec163
Create Date: 2026-06-22 07:59:19.666260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58acae84c2df'
down_revision: Union[str, None] = 'a250757ec163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history')),
    sa.UniqueConstraint('security_id', 'date', name='uq_price_history_security_date')
    )
 
    # Primary lookup: fetch all prices for a security, newest first
    op.create_index(
        "ix_price_history_security_date",
        "price_history",
        ["security_id", sa.text("date DESC")],
    )
 
    # Covering index for date-range queries across securities (e.g. "all
    # tickers on date X" for a point-in-time portfolio snapshot)
    op.create_index(
        "ix_price_history_date",
        "price_history",
        ["date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_history_date",          table_name="price_history")
    op.drop_index("ix_price_history_security_date", table_name="price_history")
    op.drop_table('price_history')
    # ### end Alembic commands ###
