"""add transfer_group_id to bank_transactions

Revision ID: a250757ec163
Revises: 91727e60c324
Create Date: 2026-06-19 04:55:21.401543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a250757ec163'
down_revision: Union[str, None] = '91727e60c324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('transfer_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_bank_transactions_transfer_group_id'), 'bank_transactions', ['transfer_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_transfer_group_id'), table_name='bank_transactions')
    op.drop_column('bank_transactions', 'transfer_group_id')
    # ### end Alembic commands ###
